//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int MaBai { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> MaPostParent { get; set; }
    
        public virtual POST_PARENT POST_PARENT { get; set; }
    }
}
